# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
# Generated by configen, do not edit.
# See https://github.com/facebookresearch/hydra/tree/master/tools/configen
# fmt: off
# isort:skip_file
# flake8: noqa

from dataclasses import dataclass, field
from omegaconf import MISSING
from pathlib import Path
from tests.test_modules import Color
from tests.test_modules import User
from typing import Any
from typing import Dict
from typing import List
from typing import Optional
from typing import Tuple
from typing import Union


@dataclass
class EmptyConf:
    _target_: str = "tests.test_modules.Empty"


@dataclass
class UntypedArgConf:
    _target_: str = "tests.test_modules.UntypedArg"
    param: Any = MISSING


@dataclass
class IntArgConf:
    _target_: str = "tests.test_modules.IntArg"
    param: int = MISSING


@dataclass
class PathArgConf:
    _target_: str = "tests.test_modules.PathArg"
    param: Path = MISSING


@dataclass
class ArgsConf:
    _target_: str = "tests.test_modules.Args"


@dataclass
class KwargsConf:
    _target_: str = "tests.test_modules.Kwargs"


@dataclass
class UnionArgConf:
    _target_: str = "tests.test_modules.UnionArg"
    param: Union[float, int] = MISSING
    param2: Optional[Union[Color, bool, str]] = None
    param3: Union[Path, str] = ""
    param4: Any = ""  # Union[DictConfig, str]
    param5: Any = ('foo', 'bar')  # Union[List[str], Tuple[str, ...], str]
    param6: Any = ('foo', 'bar')  # Union[list[str], str, tuple[str, ...]]
    param7: Union[Path, str] = ""


@dataclass
class WithLibraryClassArgConf:
    _target_: str = "tests.test_modules.WithLibraryClassArg"
    num: int = MISSING
    param: Any = MISSING  # LibraryClass


@dataclass
class IncompatibleDataclassArgConf:
    _target_: str = "tests.test_modules.IncompatibleDataclassArg"
    num: int = MISSING
    incompat: Any = MISSING  # IncompatibleDataclass


@dataclass
class WithStringDefaultConf:
    _target_: str = "tests.test_modules.WithStringDefault"
    no_default: str = MISSING
    default_str: str = "Bond, James Bond"
    none_str: Optional[str] = None


@dataclass
class WithUntypedStringDefaultConf:
    _target_: str = "tests.test_modules.WithUntypedStringDefault"
    default_str: Any = "Bond, James Bond"


@dataclass
class ListValuesConf:
    _target_: str = "tests.test_modules.ListValues"
    lst: List[str] = MISSING
    lst2: list[str] = MISSING
    enum_lst: List[Color] = MISSING
    passthrough_list: Any = MISSING  # List[LibraryClass]
    dataclass_val: List[User] = MISSING
    def_value: List[str] = field(default_factory=lambda: [])
    def_value2: list[str] = field(default_factory=lambda: [])


@dataclass
class DictValuesConf:
    _target_: str = "tests.test_modules.DictValues"
    dct: Dict[str, str] = MISSING
    dct2: dict[str, str] = MISSING
    enum_key: Dict[Color, str] = MISSING
    dataclass_val: Dict[str, User] = MISSING
    passthrough_dict: Any = MISSING  # Dict[str, LibraryClass]
    def_value: Dict[str, str] = field(default_factory=lambda: {})
    def_value2: dict[str, str] = field(default_factory=lambda: {})


@dataclass
class TuplesConf:
    _target_: str = "tests.test_modules.Tuples"
    t1: Tuple[float, float] = MISSING
    t2: tuple[float, float] = MISSING
    t3: Any = (1, 2, 3)
    t4: Tuple[float, ...] = (0.1, 0.2, 0.3)


@dataclass
class PeskySentinelUsageConf:
    _target_: str = "tests.test_modules.PeskySentinelUsage"
    foo: Any = MISSING  # PeskySentinel


@dataclass
class WithLiteralsConf:
    _target_: str = "tests.test_modules.WithLiterals"
    activation: str = MISSING
    fairness: Optional[str] = None
    bit_depth: Optional[Union[float, int]] = 5
    color1: Color = Color.BLUE
    color2: Optional[Color] = Color.GREEN
    deterministic: Optional[Union[bool, str]] = None
    mixed_type_lit: Union[Color, int, str] = 0
    unioned_mixed_type_lit: Union[Union[Color, str], int] = 47
